name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        extras: [ true, false ]
        include:
          - os: macos-latest
            python-version: '3.7'
            extras: true
          - os: windows-latest
            python-version: '3.7'
            extras: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[test]"

      - name: Install extra dependencies
        if: ${{ matrix.extras }}
        run: |
          python -m pip install -e ".[all]"

      - name: Test with pytest
        run: python -m pytest --cov=erroraffirmations tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
